apiVersion: v2
description: A Helm chart for Presenting Evidence Digitally API
name: em-ped-api
home: https://github.com/hmcts/em-ped-api
version: 0.0.4
maintainers:
  - name: HMCTS EM team
dependencies:
  - name: java
    version: 4.1.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/

